### ISSUE TITLE
LazyMobileElement locators and WinAppDriver

### ISSUE THREAD

**Issue by JameyRandall** [Magenic/MAQS#15]
I am working on automating tests for windows application using the Maqs 5.3 and the WinAppDriver. 

I would like to take advantage of the LazyElement with the WinAppDriver  but it doesnt look like it is supported.

Appium supports supports locator options that are not available in selenium
        public W FindElement(string by, string value);
        public W FindElement(By by);
        public W FindElementByAccessibilityId(string selector);
        public W FindElementByClassName(string className);
        public W FindElementByCssSelector(string cssSelector);
        public W FindElementById(string id);
        public W FindElementByLinkText(string linkText);
        public W FindElementByName(string name);
        public W FindElementByPartialLinkText(string partialLinkText);
        public W FindElementByTagName(string tagName);
        public W FindElementByXPath(string xpath); 

When I look at the LazyModbileElement under BaseAppiumTest I see it is using the OpenQA.selenium locators, not the OpenQA.Selenium.Appium locators. Shouldn't the LazyMobileElement use the Appium locators?

When I try to create a windows element and use the LazyMobileElement I get an error that it cannot convert ...BaseAppiymTest.LazyMobileElement to ...Appium.Windows.WindowsElement.  

Here are a couple code snips to help explain what I am trying to do:

 private WindowsElement EnterIDNumberField
 {
get { return this.TestObject.AppiumDriver.FindElementByAccessibilityId("1") as WindowsElement; }
 }

private WindowsElement blah
 {
            get { return new LazyMobileElement(this.TestObject, By.XPath(@"//someXPathforIdNumberField"),"element") as WindowsElement; }
        }

**Comment by jason-edstrom** [comment]
Hey Jamey,

With your casting issue,  LazyMobileElement only implements IWebElement and it fulfills the requirements by that interface.  WindowsElement is different in that respect because it implements and extends different classes and interfaces.  Since LazyMobileElement doesn't fulfill those other interface requirements, a direct cast is not possible as you are trying to implement.

In terms of the Appium selector options that you listed, those are convenience methods for the standard FindElement(By by) method call.  AccessibilityId is different, but it can share the same appium call for By.name.  If you travel down the inheritance chain for the appium driver, it is technically just an extended RemoteWebDriver with a lot of mobile magic added in.  The Appium driver gets a decent amount of functionality from the selenium driver and a number of the selenium classes can be used by the Appium driver.

I hope this helps.

**Comment by TroyWalshProf** [comment]
@JameyRandall, does Jason's answer about help?

**Comment by JameyRandall** [comment]
@TroyWalshProf
Yes, Jason's response made sense.   For now, we have put our Appium project on hold, but I am guessing we will kick off another one this year.
