### ISSUE TITLE
Support for xUnit

### ISSUE THREAD

**Issue by pjotal** [Magenic/MAQS#386]
Please implement the support to use MAQS with xUnit as well.

**Comment by TroyWalshProf** [comment]
We did talk about adding XUnit many years ago but decided against it because of how differently it hands test setup and teardown functionality which MAQS heavily relies on.

Out of curiosity, what would this give you that NUnit or MSTest do not?

**Comment by pjotal** [comment]
i understand your decision. we wanted xunit support so we could be compliant on the unit test framework choice of the rest of the company.

**Comment by FermJacob** [comment]
@TroyWalshProf xUnit has comparisions
https://xunit.net/docs/comparisons

**Comment by billros** [comment]
MAQS uses (unit test frameworks (NUnit, MSTest) to implement functional tests. You could think of it as a very thin wrapper around the framework, but we leave most of the portions "sticking out", so you can use them.  As such, you wouldn't be in violation of of the unit test framework, because you are not implementing unit tests...

The differences between the frameworks above and XUnit (as Troy alluded) make the latter incompatible with the MAQS internal design.  Some of the major benefits of MAQS (such as per test method log initialization and soft-assert cleanup) would not be possible without a completely different implementation, if at all.  These capabilities support the "run now, analyze later" approach to functional regression testing that is NOT consistent with unit testing (i.e. "if it fails, stop and fix it!").  

For these reasons, we have no plans to support XUnit framework within MAQS, at this time.
