### ISSUE TITLE
Request for improvement

### ISSUE THREAD

**Issue by pulversss** [Magenic/MAQS#7]
Good afternoon, a huge request to consider the possibility of connecting your product to the report portal Allure https://docs.qameta.io/allure/#_get_started.

Thanks you

Maksim

**Comment by TroyWalshProf** [comment]
@pulversss 
Have you tried using the Allure [NUnit](https://github.com/unickq/allure-nunit) or [MSTest
](https://github.com/allure-framework/allure-mstest) libraries?
MAQS is built on top of VSUnit and NUnit.
So as far as I can tell you don't actually need to change MAQS in order to get Allure results.

I am 95% sure the NUnit implimentation would just work if you added the Allure package and test attributes.
Example:

```
    [TestFixture]
    [AllureNUnit]
    public class SeleniumTest : BaseSeleniumTest
    {
        [OneTimeSetUp]
        public void CleanupResultDirectory()
        {
            AllureExtensions.WrapSetUpTearDownParams(() => { AllureLifecycle.Instance.CleanupResultDirectory(); },
                "Cleanup Allure Results Directory");
        }

        /// <summary>
        /// Open page test
        /// </summary>
        [Test]
        [AllureTag("NUnit", "Debug")]
        [AllureIssue("GitHub#1", "https://github.com/unickq/allure-nunit")]
        [AllureSeverity(Allure.Commons.SeverityLevel.critical)]
        [AllureFeature("Core")]
        public void RunTest()
        {
            // Do something
        }

```

**Comment by pulversss** [comment]
Thanks a lot !!!
With your help everything turned out.
