### ISSUE TITLE
Logging Config Stack overflow issue

### ISSUE THREAD

**Issue by jonreding2010** [Magenic/MAQS#703]
When trying to unit test the Logging Config, a stack overflow occurred.

**Comment by FermJacob** [comment]
@TroyWalshProf The issue is inside of 

``` csharp
public static LoggingEnabled GetLoggingEnabledSetting()
        {
            switch (Config.GetGeneralValue("Log", "NO").ToUpper())
            {
                case "YES":
                    return LoggingEnabled.YES;
                case "ONFAIL":
                    return LoggingEnabled.ONFAIL;
                case "NO":
                    return LoggingEnabled.NO;
                default:
                    throw new ArgumentException(StringProcessor.SafeFormatter($"Log value '{Config.GetGeneralValue("Log", "NO")}' is not a valid option"));
            }
        }
```

When the default is being called, the exception is being thrown, the FirstChanceHandler is catching this exception.  Inside the FirstChanceHandler, it is performing the same call to GetLoggingEnabledSetting which is causing a stack overflow.

My proposal is to have NO and default perform the same action.  Thoughts?
